language: crystal
crystal:
  - latest

script:
  - make test
  - crystal tool format src/ --check
  - crystal docs

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  project_name: crest
  on:
    branch: master
  local_dir: docs
