language: crystal
crystal:
  - latest

script:
  - make test
  - crystal tool format src/ --check
  - bin/ameba src/
  - crystal docs

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  project_name: crest
  local_dir: docs
  # Workaround for travis-ci/travis-ci#9312
  edge:
    branch: pages-ivar-set
  on:
    branch: master
