TEST_SERVER_HOST  = "127.0.0.1"
TEST_SERVER_PORT  = 4567
TEST_SERVER_URL   = "http://#{TEST_SERVER_HOST}:#{TEST_SERVER_PORT}"
ALT_TEST_SERVER_HOST = "127.0.0.1"
ALT_TEST_SERVER_PORT = 4568
ALT_TEST_SERVER_URL  = "http://#{ALT_TEST_SERVER_HOST}:#{ALT_TEST_SERVER_PORT}"
PROXY_SERVER_HOST = "127.0.0.1"
PROXY_SERVER_PORT = 8088
